Swaggy.App/Areas/Admin/Controllers/CustomerController.cs
using AutoMapper;
using Swaggy.App;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMAppDataLayer;
namespace Swaggy.App.Areas.Admin.Controllers
{
    public class CustomerController : BaseController
    {
        public CustomerController(){
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Customer, CMAppDataLayer.Customer>();
            });
        }

        // GET: Admin/Customer
        public ActionResult Index()
        {
            var customers = _ctx.Customers.ToList();
            var model = Mapper.Map<IEnumerable<Customer>, IEnumerable<CMAppDataLayer.Customer>>(customers);
            return View("Index", model);
        }

        // GET: Admin/Customer/Details/5
        public ActionResult Details(int id)
        {
            var customer = _ctx.Customers.FirstOrDefault(c => c.CID == id);
            var model = Mapper.Map<Customer, CMAppDataLayer.Customer>(customer);
            return View(model);
        }

        // GET: Admin/Customer/Delete/5
        public ActionResult Delete(int id)
        {
            var customer = _ctx.Customers.FirstOrDefault(c => c.CID == id);
            _ctx.Customers.Remove(customer);
            _ctx.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Swaggy.App/Areas/Admin/Controllers/OrderController.cs
using AutoMapper;
using Swaggy.App;
using Swaggy.App.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMAppDataLayer;
namespace Swaggy.App.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController()
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Order, CMAppDataLayer.Models.Admin.OrderModel>();
            });
        }

        // GET: Admin/Order
        public ActionResult Index()
        {
            var orders = _ctx.Orders;
            var model = Mapper.Map<IEnumerable<Order>, IEnumerable<CMAppDataLayer.Models.Admin.OrderModel>>(orders);
            return View(model);
        }

        // GET: Admin/Order/Details/5
        public ActionResult Details(int id)
        {
            var order = _ctx.Orders.FirstOrDefault(o => o.OrderID == id);
            var model = Mapper.Map<CMAppDataLayer.Models.Admin.OrderModel>(order);
            return View(model);
        }
    }
}

Swaggy.App/Areas/Admin/Controllers/StockController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Swaggy.App.Areas.Admin.Controllers
{
    public class StockController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chart()
        {
            var units = new List<int>();
            var rol = new List<int>();
            var labels = new List<string>();
            foreach (var i in _ctx.Products)
            {
                units.Add(i.UnitsInStock);
                rol.Add(i.ROL);
                labels.Add(i.PName);
            }
            List<object> data = new List<object> { new {
                label = "Units in Stock",
                backgroundColor = "rgba(255, 99, 132, 0.6)",
                data = units
            }, new {
                label = "Re-Order-Level",
                backgroundColor = "rgba(153, 102, 255, 0.6)",
                data = rol
            }, labels};

            var result = Json(data.ToArray(), JsonRequestBehavior.AllowGet);
            return result;
        }

        private string _randomColor()
        {
            Random randomGen = new Random();
            KnownColor[] names = (KnownColor[])Enum.GetValues(typeof(KnownColor));
            KnownColor randomColorName = names[randomGen.Next(names.Length)];
            Color c = Color.FromKnownColor(randomColorName);
            return "#" + c.R.ToString("X2") + c.G.ToString("X2") + c.B.ToString("X2");
        }
    }
}

Swaggy.App/Areas/Admin/Controllers/SupplierController.cs
using AutoMapper;
using Swaggy.App;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMAppDataLayer;
namespace Swaggy.App.Areas.Admin.Controllers
{
    public class SupplierController : BaseController
    {
        public SupplierController()
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Supplier,Supplier>();
            }); 
        }

        // GET: Admin/Supplier
        public ActionResult Index()
        {
            var suppliers = _ctx.Suppliers.ToList();
            var model = Mapper.Map<List<Supplier>, IEnumerable<Supplier>>(suppliers);
            return View(model);
        }

        private Supplier _get(int id)
        {
            var supplier = _ctx.Suppliers.FirstOrDefault(s => s.SID == id);
            return supplier;
        }

        // GET: Admin/Supplier/Details/5
        public ActionResult Details(int id)
        {
            var model = _get(id);
            return View(model);
        }

        // GET: Admin/Supplier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Supplier/Create
        [HttpPost]
        public ActionResult Create(Supplier supplier)
        {
            try
            {
                // TODO: Add insert logic here
                _ctx.Suppliers.Add(supplier);
                _ctx.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(supplier);
            }
        }

        // GET: Admin/Supplier/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _get(id);
            return View(model);
        }

        // POST: Admin/Supplier/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Supplier model)
        {
            try
            {
                // TODO: Add update logic here
                Supplier supplier = _ctx.Suppliers.FirstOrDefault(s => s.SID == id);
                supplier.SName = model.SName;
                supplier.Address1 = model.Address1;
                supplier.Address2 = model.Address2;
                supplier.Email = model.Email;
                supplier.Phone = model.Phone;
                supplier.Postcode = model.Postcode;
                supplier.State = model.State;
                supplier.Suburb = model.Suburb;
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Admin/Supplier/Delete/5
        public ActionResult Delete(int id)
        {
            var supplier = _get(id);
            _ctx.Suppliers.Remove(supplier);
            _ctx.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Swaggy.App/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Canteen Online</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
    <style>
        /* default css start */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Open Sans', sans-serif;
            font-size: 14px;
            font-weight: 400;
            line-height: 20px;
        }


        .header-area {
            background: linear-gradient(rgba(0,0,0,.3), rgba(0,0,0,.5)), url(https://images.unsplash.com/photo-1528353518104-dbd48bee7bc4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80);
            background-position: center center;
            background-size: cover;
        }
        /* default css end */


        /* navbar regular css start */
        .navbar-area {
            background: rgba(0,0,0,.6);
            border-bottom: 1px solid #000;
        }

        .site-navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        a.site-logo {
            font-size: 26px;
            font-weight: 800;
            text-transform: uppercase;
            color: #fff;
            text-decoration: none;
        }

        .site-navbar ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
        }

            .site-navbar ul li a {
                color: #fff;
                padding: 15px;
                display: block;
                text-decoration: none;
                text-transform: uppercase;
            }

                .site-navbar ul li a:hover {
                    background: rgba(255,255,255,.1);
                }
        /* navbar regular css end */


        /* nav-toggler css start */
        .nav-toggler {
            border: 3px solid #fff;
            padding: 5px;
            background-color: transparent;
            cursor: pointer;
            height: 39px;
            display: none;
        }

            .nav-toggler span,
            .nav-toggler span:before,
            .nav-toggler span:after {
                width: 28px;
                height: 3px;
                background-color: #fff;
                display: block;
                transition: .3s;
            }

                .nav-toggler span:before {
                    content: '';
                    transform: translateY(-9px);
                }

                .nav-toggler span:after {
                    content: '';
                    transform: translateY(6px);
                }

            .nav-toggler.toggler-open span {
                background-color: transparent;
            }

                .nav-toggler.toggler-open span:before {
                    transform: translateY(0px) rotate(45deg);
                }

                .nav-toggler.toggler-open span:after {
                    transform: translateY(-3px) rotate(-45deg);
                }
        /* nav-toggler css start */


        /* intro-area css start */
        .intro-area {
            height: fit-content;
            display: flex;
            align-items: center;
            text-align: center;
            color: #fff;
        }

            .intro-area h2 {
                font-size: 50px;
                font-weight: 300;
                line-height: 50px;
                margin-bottom: 25px;
            }

            .intro-area p {
                font-size: 18px;
            }
        /* intro-area css end */
        /* mobile breakpoint end */
    </style>
    <script>// define all UI variable
        const navToggler = document.querySelector('.nav-toggler');
        const navMenu = document.querySelector('.site-navbar ul');
        const navLinks = document.querySelectorAll('.site-navbar a');

        // load all event listners
        allEventListners();

        // functions of all event listners
        function allEventListners() {
            // toggler icon click event
            navToggler.addEventListener('click', togglerClick);
            // nav links click event
            navLinks.forEach(elem => elem.addEventListener('click', navLinkClick));
        }

        // togglerClick function
        function togglerClick() {
            navToggler.classList.toggle('toggler-open');
            navMenu.classList.toggle('open');
        }

        // navLinkClick function
        function navLinkClick() {
            if (navMenu.classList.contains('open')) {
                navToggler.click();
            }
        }</script>
</head>
<body>

    <header class="header-area">
        <!-- site-navbar start -->
        <div class="navbar-area">
            <div class="container">
                <nav class="site-navbar">
                    <!-- site logo -->
                    @if (Request.IsAuthenticated)
                    {@*@Html.ActionLink("Canteen Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                                    <a href="/Home/Index" class="site-logo"><img src="~/Images/Products/swaggy1.png" style="width:180px;height:80px" /></a> }
                                                else
                                                { @*@Html.ActionLink("Canteen Management", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })*@
                                                                <a href="/Account/Login" class="site-logo"><img src="~/Images/Products/swaggy1.png" style="width:180px;height:80px" /></a>}

                    <!-- site menu/nav -->
                    <ul>
                        @if (Request.IsAuthenticated)
                        {
            <li>@Html.ActionLink("Product", "Index", "Product", null, null)</li>
                            <li>@Html.ActionLink("Suppliers", "Index", "Supplier", null, null)</li>
                                            <li>@Html.ActionLink("Customers", "Index", "Customer", null, null)</li>
                                                            <li>@Html.ActionLink("Orders", "Index", "Order", null, null)</li>
                                                                            <li>@*@Html.ActionLink("Stocks", "Index", "Stock", null, null)*@</li>
}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Shop", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div><!-- navbar-area end -->

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Canteen Online</p>
            </footer>
        </div>
    </header>


   
   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>